version: 0.2

env:
  variables:
    S3_ARTIFACT: "artifacts-aws-test"
    
phases:
  install:
    commands:
      - ls
      - python3 -m pip install --target . -r requirements.txt
  build:
    commands:
      - echo $S3_ARTIFACT
      - ls
      - zip -r artifact.zip .
      - aws cloudformation package --template-file ./cloudformation/cloudformation.yaml --s3-bucket $S3_ARTIFACT --output-template-file ./cloudformation.yaml
artifacts:
  files:
    - cloudformation.yaml